#!/bin/bash -ex

##############################################################################
# This file is part of RetroCRT (https://github.com/xovox/RetroCRT)
#
# RetroCRT is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# RetroCRT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with RetroCRT.  If not, see <https://www.gnu.org/licenses/>.
##############################################################################

#sudo apt update
#sudo apt -y dist-upgrade
#sudo find /dev/shm -name '*deb' -delete

killall emulationstation
cd $HOME/RetroPie-Setup
git pull
sudo ./retropie_setup.sh
sudo find /dev/shm -name '*deb' -delete

cd $HOME/RetroCRT
git pull
export TMPDIR=/dev/shm/pip
mkdir -pv $TMPDIR
./retrocrt_setup.sh
echo $HOME/RetroPie/splashscreens/RetroCRT.mp4 | sudo tee /etc/splashscreen.list
sudo find /dev/shm -name '*deb' -delete
