#!/bin/bash -e

##############################################################################
# This file is part of RetroCRT (https://github.com/xovox/RetroCRT)
#
# RetroCRT is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# RetroCRT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with RetroCRT.  If not, see <https://www.gnu.org/licenses/>.
##############################################################################

##############################################################################
# retrocrt-finalimage (c) 2020 duncan brown (http://github.com/xovox)
#
# this script downloads a retropie image & preps it to become a RetroCRT image
#
# - creates loopback device
# - takes data from tested SD card & writes to loopback
# - mounts loopback
# - re-enables filesystem growth
# - writes new image to tested SD card for final test
# - renames image to today's date
# - generates an HTML version of the README.md & MANUAL.md
# - creates a 7z file with the image, HTML & LICENSE.txt
# 
##############################################################################

rcrtimage="$1"
blockdev="$2"

if [ ! "$blockdev" ]; then
	echo $0 "[image] [blockdev]"
	exit
fi

rcrtbanner() {
	rcrtbanner="$1"
	rcrtbwidth="$[ $(wc -L <<< "$rcrtbanner") + 2 ]"
	echo
	printf %${rcrtbwidth}s | tr ' ' '='
        printf "\n%*s\n" $(((${#rcrtbanner}+$rcrtbwidth)/2)) "$rcrtbanner"
	printf %${rcrtbwidth}s | tr ' ' '='
	echo
	echo
}


loopback="$(sudo losetup -Pf --show $rcrtimage)"
bootpart=${loopback}p1
rootpart=${loopback}p2
bootmnt="$(mktemp -d)"
rootmnt="$(mktemp -d)"

for i in 1 2 ; do
	rcrtbanner "${blockdev}$i -> $rcrtimage"
	sudo dd if=${blockdev}$i bs=1M of=${loopback}p${i} status=progress
done

rcrtbanner "fsck root partition"

sudo e2fsck -f $rootpart

rcrtbanner "re-enabling resizing on first boot"

sudo mount -v $bootpart $bootmnt
sudo mount -v $rootpart $rootmnt

sudo sed -i 's|$| init=/usr/lib/raspi-config/init_resize.sh|' $bootmnt/cmdline.txt
sudo sed -i '/RetroCRT/d' $rootmnt/etc/init.d/resize2fs_once

sudo umount -v $bootmnt
sudo umount -v $rootmnt
sudo losetup -D $loopback

rcrtbanner "$rcrtimage -> ${blockdev}$i"
pv "$rcrtimage" | sudo dd bs=1M of=$blockdev

rcrtbanner "running sync"

sleep 5
sudo sync

rcrtbanner "creating archive"

releasedir="/var/www/html/RetroCRT-Releases/RetroCRT-$(date +%Y%m%d)"

mkdir -pv "$releasedir"

mv -v $rcrtimage $releasedir/

for i in README MANUAL; do
	markdown ../$i.md > $releasedir/$i.html
done

cp ../LICENSE.txt $releasedir/

cd $releasedir/..

7z a RetroCRT-$(date +%Y%m%d).7z RetroCRT-$(date +%Y%m%d)
