#!/bin/bash -ex

##############################################################################
# This file is part of RetroCRT (https://github.com/xovox/RetroCRT)
#
# RetroCRT is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# RetroCRT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with RetroCRT.  If not, see <https://www.gnu.org/licenses/>.
##############################################################################

##############################################################################
# newSD (c) 2020 duncan brown (http://github.com/xovox)
#
# this script is used to speed up building new-from-scratch retropie machines
# to test with RetroCRT, though it should be fine to use with whatever.  it
# currently only works under GNU/Linux, though macOS compatibility is coming
##############################################################################

if [ ! "$2" ]; then
	echo "$0 [raspberry_pi_image] [dest_block_device]"
	exit
fi

clear

doUncompress() {
	if [[ "$image" =~ .*bz2 ]]; then
		pv -cN archive | pbzip2 --decompress
	elif [[ "$image" =~ .*gz ]]; then
		pv -cN archive | gunzip
	else
		pv -cN image
	fi < "$image"
}

image="$1"
block="$2"

test -b "$block"

sudo dd if=/dev/zero bs=1M count=1 of="$block"
sudo sync
sleep 2
sudo partprobe $block
sleep 2
doUncompress "$image" | pv -cN $block | sudo dd bs=1M of="$block"
sudo sync
sleep 2
sudo partprobe $block
sleep 2

bootMount=$(mktemp -d)
rootMount=$(mktemp -d)

homeDir=$rootMount/home/pi

sudo mount ${block}1 $bootMount
sudo mount ${block}2 $rootMount
sudo touch $bootMount/ssh

if [ "$ssh" ]; then
	rsync -av --progress ~/RetroPieSD/.ssh/ $homeDir/.ssh/
    chmod -Rc go= $homeDir/.ssh
fi

if [ "$rcrt" ]; then
    cd $homeDir
    git clone --depth 1 git@github.com:xovox/RetroCRT.git
fi

if [ "$splash" ]; then
	rsync -av --progress ~/Files/splash/ $homeDir/RetroPie/splashscreens/
fi

#if [ -d $rootMount/home/pi ]; then
	sudo chown -Rc 1000.1000 $homeDir
#fi

sleep 5
sudo sync
sleep 5

for mount in $bootMount $rootMount ; do
	sudo umount $mount
	sudo rm -rfv $mount
done

sudo sync

rm -rf $bootMount

clear; reset ; clear
